googleurl=https://www.google.com/?
googlesignin=https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&dsh=S1997084078%3A1775816381592695&rip=1&sacu=1&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&ifkv=AT1y2_XopmIDBHWqCT3vzDxdjRxanObGK4xJ63SgZln6WVSl0x8D0FOErwzVtoSnC0TBl5ujHw7VYA
browser=firefox
tiny=https://tinypng.com/
amazonin=https://www.amazon.in
fburl=https://www.facebook.com
fxbrowser=chrome
interneturl=https://the-internet.herokuapp.com/javascript_alerts
youtube=https://www.youtube.com/results?search_query=Trending
youtubevideo=https://www.youtube.com/results?search_query=trending+comedy+videos
amazonurl=http://amazon.in/deals?ref_=nav_cs_gb
amazonscroll=https://www.amazon.in/Apple-iPhone-15-128-GB/dp/B0CHX2F5QT/ref=sr_1_1_sspa?dib=eyJ2IjoiMSJ9.8-aKrERwPzdGyJWfWOa56I4wwdlI59jT8Bz9mNMoRuJhDPQn-fIYfKJxxKAv6p4v1WokuXVTy6CEak1Vh-NyyTAmDXkLE8-YpWVSsG52cuzHWfPGQmEHKBuZ28lHimBXoQFiBwUPbI-ZeU-uwbRmEyhJD5fUfpVpnDipADtkVUwmxr6VbbPQvv5LFbY1WR9N3gcPO9_X-kNXIO6PoI6QGW7ShecF0XyC5lFbzvZ5rcM._JVkc7BD-ArTQsOMOX7UqQM0g4lkYjz4Kfj0gsZeNMA&dib_tag=se&keywords=iphone%2B15&qid=1722790570&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1
internet=https://the-internet.herokuapp.com/iframe
rolls=https://www.rolls-royce.com
git=https://www.github.com/
tubeyou=https://www.youtube.com/watch?v=nIHyr_fp_yI